<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
    <PackageReference Include="xunit.v3" Version="4.0.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="4.0.0" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="NLaya.Testing" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../NLaya.Testing/NLaya.Testing.csproj" />
    <ProjectReference Include="../../src/NLaya/NLaya.csproj" />
    <ProjectReference Include="../../src/NLaya.TorchSharp/NLaya.TorchSharp.csproj" />
    <ProjectReference Include="../../src/NLaya.Onnx/NLaya.Onnx.csproj" />
    <ProjectReference Include="../../src/NLaya.Extensions.AI/NLaya.Extensions.AI.csproj" />
    <ProjectReference Include="../../src/NLaya.ML/NLaya.ML.csproj" />

    <PackageReference Include="TorchSharp-cpu" Version="0.107.0" />
  </ItemGroup>
</Project>
